CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    total_price DOUBLE PRECISION,
    status VARCHAR(255)
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT,
    quantity INTEGER,
    price DOUBLE PRECISION,
    order_id BIGINT,
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);
